# Generated by Django 5.1.1 on 2024-10-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('source', 'Source'), ('target', 'Target')], max_length=6)),
                ('record_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('source', 'record_id')},
            },
        ),
    ]
